-- @diagnostic disable: undefined-field
-- require('nvim-treesitter.configs').setup {
--     ensure_installed = { "lua", "python", "javascript", "c", "cpp" },
--     highlight = {
--         enable = true,
--         additional_vim_regex_highlighting = true,
--     },
-- }
